name: Catbreeds
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.4.3 <4.0.0'

dependencies: 
  flutter: 
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Get
  get: ^4.6.6
  get_storage: ^2.1.1

  cached_network_image: ^3.3.1
  dio_cache_interceptor: ^3.5.0
  dio: ^5.4.3+1
  flutter_dotenv: ^5.1.0
  flutter_native_splash: ^2.4.1
  intl: ^0.19.0
  json_annotation: ^4.9.0
  loading_animation_widget: ^1.2.0+4
  url_launcher: ^6.3.0

dev_dependencies: 
  build_runner: ^2.4.11
  flutter_lints: ^4.0.0
  flutter_test: 
    sdk: flutter
  json_serializable: ^6.8.0

flutter: 
  uses-material-design: true
  generate: true

  assets:
  - .env
  - assets/images/
  
flutter_native_splash:
  color: "#ffffff"
  image: assets/images/splash.png
  android_12:
    image: assets/images/splash.png
