// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'cat.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

Cat _$CatFromJson(Map<String, dynamic> json) => Cat(
      adaptability: (json['adaptability'] as num?)?.toInt(),
      affectionLevel: (json['affection_level'] as num?)?.toInt(),
      altNames: json['alt_names'] as String?,
      cfaUrl: json['cfa_url'] as String?,
      childFriendly: (json['child_friendly'] as num?)?.toInt(),
      countryCode: json['country_code'] as String?,
      countryCodes: json['country_codes'] as String?,
      description: json['description'] as String?,
      dogFriendly: (json['dog_friendly'] as num?)?.toInt(),
      energyLevel: (json['energy_level'] as num?)?.toInt(),
      experimental: (json['experimental'] as num?)?.toInt(),
      grooming: (json['grooming'] as num?)?.toInt(),
      hairless: (json['hairless'] as num?)?.toInt(),
      healthIssues: (json['health_issues'] as num?)?.toInt(),
      hypoallergenic: (json['hypoallergenic'] as num?)?.toInt(),
      id: json['id'] as String?,
      indoor: (json['indoor'] as num?)?.toInt(),
      intelligence: (json['intelligence'] as num?)?.toInt(),
      lap: (json['lap'] as num?)?.toInt(),
      lifeSpan: json['life_span'] as String?,
      name: json['name'] as String?,
      natural: (json['natural'] as num?)?.toInt(),
      origin: json['origin'] as String?,
      rare: (json['rare'] as num?)?.toInt(),
      referenceImageId: json['reference_image_id'] as String?,
      rex: (json['rex'] as num?)?.toInt(),
      sheddingLevel: (json['shedding_level'] as num?)?.toInt(),
      shortLegs: (json['short_legs'] as num?)?.toInt(),
      socialNeeds: (json['social_needs'] as num?)?.toInt(),
      strangerFriendly: (json['stranger_friendly'] as num?)?.toInt(),
      suppressedTail: (json['suppressed_tail'] as num?)?.toInt(),
      temperament: json['temperament'] as String?,
      vcahospitalsUrl: json['vcahospitals_url'] as String?,
      vetstreetUrl: json['vetstreet_url'] as String?,
      vocalisation: (json['vocalisation'] as num?)?.toInt(),
      weight: json['weight'] == null
          ? null
          : Weight.fromJson(json['weight'] as Map<String, dynamic>),
      wikipediaUrl: json['wikipedia_url'] as String?,
    );

Map<String, dynamic> _$CatToJson(Cat instance) => <String, dynamic>{
      'adaptability': instance.adaptability,
      'affection_level': instance.affectionLevel,
      'child_friendly': instance.childFriendly,
      'dog_friendly': instance.dogFriendly,
      'energy_level': instance.energyLevel,
      'experimental': instance.experimental,
      'grooming': instance.grooming,
      'hairless': instance.hairless,
      'health_issues': instance.healthIssues,
      'hypoallergenic': instance.hypoallergenic,
      'indoor': instance.indoor,
      'intelligence': instance.intelligence,
      'lap': instance.lap,
      'natural': instance.natural,
      'rare': instance.rare,
      'rex': instance.rex,
      'shedding_level': instance.sheddingLevel,
      'short_legs': instance.shortLegs,
      'social_needs': instance.socialNeeds,
      'stranger_friendly': instance.strangerFriendly,
      'suppressed_tail': instance.suppressedTail,
      'vocalisation': instance.vocalisation,
      'alt_names': instance.altNames,
      'cfa_url': instance.cfaUrl,
      'country_code': instance.countryCode,
      'country_codes': instance.countryCodes,
      'description': instance.description,
      'id': instance.id,
      'life_span': instance.lifeSpan,
      'name': instance.name,
      'origin': instance.origin,
      'reference_image_id': instance.referenceImageId,
      'temperament': instance.temperament,
      'vcahospitals_url': instance.vcahospitalsUrl,
      'vetstreet_url': instance.vetstreetUrl,
      'wikipedia_url': instance.wikipediaUrl,
      'weight': instance.weight,
    };
