// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'cat.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

Cat _$CatFromJson(Map<String, dynamic> json) => Cat(
      adaptability: (json['adaptability'] as num?)?.toInt(),
      affectionLevel: (json['affectionLevel'] as num?)?.toInt(),
      altNames: json['altNames'] as String?,
      cfaUrl: json['cfaUrl'] as String?,
      childFriendly: (json['childFriendly'] as num?)?.toInt(),
      countryCode: json['countryCode'] as String?,
      countryCodes: json['countryCodes'] as String?,
      description: json['description'] as String?,
      dogFriendly: (json['dogFriendly'] as num?)?.toInt(),
      energyLevel: (json['energyLevel'] as num?)?.toInt(),
      experimental: (json['experimental'] as num?)?.toInt(),
      grooming: (json['grooming'] as num?)?.toInt(),
      hairless: (json['hairless'] as num?)?.toInt(),
      healthIssues: (json['healthIssues'] as num?)?.toInt(),
      hypoallergenic: (json['hypoallergenic'] as num?)?.toInt(),
      id: json['id'] as String?,
      indoor: (json['indoor'] as num?)?.toInt(),
      intelligence: (json['intelligence'] as num?)?.toInt(),
      lap: (json['lap'] as num?)?.toInt(),
      lifeSpan: json['lifeSpan'] as String?,
      name: json['name'] as String?,
      natural: (json['natural'] as num?)?.toInt(),
      origin: json['origin'] as String?,
      rare: (json['rare'] as num?)?.toInt(),
      referenceImageId: json['referenceImageId'] as String?,
      rex: (json['rex'] as num?)?.toInt(),
      sheddingLevel: (json['sheddingLevel'] as num?)?.toInt(),
      shortLegs: (json['shortLegs'] as num?)?.toInt(),
      socialNeeds: (json['socialNeeds'] as num?)?.toInt(),
      strangerFriendly: (json['strangerFriendly'] as num?)?.toInt(),
      suppressedTail: (json['suppressedTail'] as num?)?.toInt(),
      temperament: json['temperament'] as String?,
      vcahospitalsUrl: json['vcahospitalsUrl'] as String?,
      vetstreetUrl: json['vetstreetUrl'] as String?,
      vocalisation: (json['vocalisation'] as num?)?.toInt(),
      weight: json['weight'] == null
          ? null
          : Weight.fromJson(json['weight'] as Map<String, dynamic>),
      wikipediaUrl: json['wikipediaUrl'] as String?,
    );

Map<String, dynamic> _$CatToJson(Cat instance) => <String, dynamic>{
      'adaptability': instance.adaptability,
      'affectionLevel': instance.affectionLevel,
      'childFriendly': instance.childFriendly,
      'dogFriendly': instance.dogFriendly,
      'energyLevel': instance.energyLevel,
      'experimental': instance.experimental,
      'grooming': instance.grooming,
      'hairless': instance.hairless,
      'healthIssues': instance.healthIssues,
      'hypoallergenic': instance.hypoallergenic,
      'indoor': instance.indoor,
      'intelligence': instance.intelligence,
      'lap': instance.lap,
      'natural': instance.natural,
      'rare': instance.rare,
      'rex': instance.rex,
      'sheddingLevel': instance.sheddingLevel,
      'shortLegs': instance.shortLegs,
      'socialNeeds': instance.socialNeeds,
      'strangerFriendly': instance.strangerFriendly,
      'suppressedTail': instance.suppressedTail,
      'vocalisation': instance.vocalisation,
      'altNames': instance.altNames,
      'cfaUrl': instance.cfaUrl,
      'countryCode': instance.countryCode,
      'countryCodes': instance.countryCodes,
      'description': instance.description,
      'id': instance.id,
      'lifeSpan': instance.lifeSpan,
      'name': instance.name,
      'origin': instance.origin,
      'referenceImageId': instance.referenceImageId,
      'temperament': instance.temperament,
      'vcahospitalsUrl': instance.vcahospitalsUrl,
      'vetstreetUrl': instance.vetstreetUrl,
      'wikipediaUrl': instance.wikipediaUrl,
      'weight': instance.weight,
    };
